FROM arm32v7/golang:1.19-alpine

COPY / /src
WORKDIR /src
RUN apk add --no-cache gcc musl-dev
RUN go build .

FROM alpine:3.17

COPY --from=0 /src/routeros-fletsv6-companion /routeros-fletsv6-companion

CMD ["/routeros-fletsv6-companion"]
